set(PATCH_DIR ${CMAKE_CURRENT_SOURCE_DIR}/cmake)

CPMAddPackage(
  NAME "Eigen3"

  GIT_REPOSITORY "https://github.com/hexagon-geo-surv/eigen.git"
  GIT_TAG "3.4.0"
  OPTIONS
  "BUILD_TESTING OFF"
  "EIGEN_BUILD_DOC OFF"
  "EIGEN_LEAVE_TEST_IN_ALL_TARGET OFF"
  "EIGEN_BUILD_PKGCONFIG OFF"
)

if(BMF_BUILD_CLI)
  CPMAddPackage(
    NAME "cli11"

    GIT_REPOSITORY "https://github.com/CLIUtils/CLI11"
    GIT_TAG "v2.1.2"
  )
endif()

CPMAddPackage(
  NAME "libigl"

  GIT_REPOSITORY "https://github.com/libigl/libigl.git"
  GIT_TAG "5da64bcbb581d189bef4f3b5cb503e03e0d94d99"
  OPTIONS
  "LIBIGL_SKIP_DOWNLOAD ON"
  "LIBIGL_USE_STATIC_LIBRARY OFF"
  "LIBIGL_COPYLEFT_COMISO OFF"
  "LIBIGL_EMBREE OFF"
  "LIBIGL_OPENGL OFF"
  "LIBIGL_GLFW OFF"
  "LIBIGL_IMGUI OFF"
  "LIBIGL_PNG OFF"
  "LIBIGL_RESTRICTED_TRIANGLE OFF"
  "LIBIGL_PREDICATES OFF"
  "LIBIGL_COPYLEFT_TETGEN OFF"
  "LIBIGL_WITH_XML OFF"
)
